<?php
// namespace
namespace icore\cache;

use icore\Cache;
use icore\Model;
use icore\Utilities;

class PageCache extends Cache
{
	// class static methods
	protected static function & _instance_()
	{
		static $instance;
		return $instance;
	}

	public function __construct()
	{
		parent::__construct();

		// cache file
		$this->setKey(VAR_CACHE_DIR . '/pagecache_' . md5(CONFIG_FILE . serialize($_GET)));
	}

	public function isCached()
	{
		// page cache is not valid for dummy, json and cli
		if (in_array($this->_app->router->entry, array('dummy', 'json', 'cli')))
		{
			return false;
		}

		// module-cachetime
		if ($this->_app->db)
		{
			$model = new Model('module_cachetime');
			$model->item(array('module = ?' => $this->_app->router->module));
			if (isset($model['cachetime']))
			{
				$time = time() - Utilities::string2seconds($model['cachetime']);
				return file_exists($this->_key) && filemtime($this->_key) > $time;
			}
		}

		return parent::isCached();
	}

	public function saveCache(& $string)
	{
		$string = preg_replace('|<!--.*?-->|', '', str_replace("\n", '', $string)) . "\n" . '<!-- Generated by iCore cache/PageCache On ' . date('Y-m-d H:i:s') . " -->";
		return parent::saveCache($string);
	}
}
